import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import { CartProvider } from "@/context/CartContext";
import { UserProvider } from "@/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cake Store App",
  description: "Generated by glad k",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <UserProvider>
      <CartProvider>
        <html lang="en">
          <body className={inter.className}>
            <NavBar />
            {children}
            <Footer />
            <ScrollToTop />
          </body>
        </html>
      </CartProvider>
    </UserProvider>
  );
}
