import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import { CartProvider } from "@/context/CartContext";
import { UserProvider } from "@/context/UserContext";
import { WishlistProvider } from "@/context/WishlistContext";
import { SearchProvider } from "@/context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cake Store App",
  description: "Generated by glad k",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <UserProvider>
      <CartProvider>
        <WishlistProvider>
          <SearchProvider>
            <html lang="en">
              <body className={inter.className}>
                <NavBar />
                {children}
                <Footer />
                <ScrollToTop />
              </body>
            </html>
          </SearchProvider>
        </WishlistProvider>
      </CartProvider>
    </UserProvider>
  );
}
